name: Instructor Tests

on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      # Checkout official tests
      uses: actions/checkout@v2
      with:
        repository: bjucps209/submission-tests
        path: tests
    # Checkout student submission
    - uses: actions/checkout@v2
      with:
        path: submission
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'    
    # Execute tests
    - name: Run tests
      run: bash tests/rungh.sh
      
